### ISSUE TITLE
Student ranking system & information input

### ISSUE THREAD

**Issue by thegargiulian** [kkbrum/ULA-app#22]
Set up student ranking system, including necessary error checks

**Comment by thegargiulian** [comment]
Also add appropriate input fields to record necessary student meta data

**Comment by ghost** [comment]
- Need to fix the width of the columns for data input, the datatable exceeds size of computer screen and requires scrolling to see the whole thing.

- Create an observeEvent for Whether Taken Class Before selection. i.e. selecting "Y" then leads to more data input options; selecting "N" leads to answering "Why do you think you are suitable for this course" only.
